# Generated by Django 5.0.4 on 2026-04-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingreport',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='scansession',
            name='operator',
        ),
    ]
