# Generated by Django 5.0.4 on 2026-04-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_shelfslot_unique_together_and_more'),
        ('scanner', '0002_remove_missingreport_resolved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingreport',
            name='expected_slot',
        ),
        migrations.AddField(
            model_name='missingreport',
            name='expected_shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_reports', to='inventory.shelf'),
        ),
    ]
