# Generated by Django 5.0.4 on 2026-04-20 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration_days', models.PositiveIntegerField(default=365)),
                ('max_books_allowed', models.PositiveIntegerField(default=3)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('can_reserve', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Membership Type',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('membership_start', models.DateField(auto_now_add=True)),
                ('membership_expiry', models.DateField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.membershiptype')),
            ],
            options={
                'verbose_name': 'Member',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['member_id'], name='members_mem_member__1c9876_idx')],
            },
        ),
    ]
