# Generated by Django 5.0.4 on 2026-04-20 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('floor', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Section',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('name', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('row_number', models.PositiveIntegerField()),
                ('column_number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='inventory.section')),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShelfSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slot_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=20)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='inventory.shelf')),
            ],
            options={
                'verbose_name': 'Shelf Slot',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rfid_tag', models.CharField(db_index=True, help_text='Unique RFID tag hex ID attached to this copy', max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('accession_number', models.CharField(help_text='Library accession/catalog number', max_length=50, unique=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('withdrawn', 'Withdrawn')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('issued', 'Issued'), ('reserved', 'Reserved'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('in_transit', 'In Transit'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.book')),
                ('assigned_slot', models.ForeignKey(blank=True, help_text='Expected home position of this copy on a shelf', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_copies', to='inventory.shelfslot')),
                ('last_scanned_slot', models.ForeignKey(blank=True, help_text='Last confirmed physical location from scanner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_copies', to='inventory.shelfslot')),
            ],
            options={
                'verbose_name': 'Book Copy',
                'verbose_name_plural': 'Book Copies',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='shelf',
            index=models.Index(fields=['code'], name='inventory_s_code_e2cf5a_idx'),
        ),
        migrations.AddIndex(
            model_name='shelfslot',
            index=models.Index(fields=['shelf', 'slot_number'], name='inventory_s_shelf_i_93a9a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shelfslot',
            unique_together={('shelf', 'slot_number')},
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['rfid_tag'], name='inventory_b_rfid_ta_3bec6f_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['status'], name='inventory_b_status_6f43c7_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['assigned_slot'], name='inventory_b_assigne_f4a625_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['barcode'], name='inventory_b_barcode_9cff1a_idx'),
        ),
    ]
