# Generated by Django 5.0.4 on 2026-04-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='rfid_tag',
            field=models.CharField(blank=True, help_text='RFID tag ID attached to the physical shelf itself', max_length=100, null=True, unique=True),
        ),
    ]
