# Generated by Django 5.0.4 on 2026-04-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0002_shelf_rfid_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shelfslot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shelfslot',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='last_scanned_slot',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='assigned_slot',
        ),
        migrations.RemoveIndex(
            model_name='bookcopy',
            name='inventory_b_assigne_f4a625_idx',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='assigned_shelf',
            field=models.ForeignKey(blank=True, help_text='Expected home shelf of this copy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_copies', to='inventory.shelf'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='last_scanned_shelf',
            field=models.ForeignKey(blank=True, help_text='Last confirmed shelf location from scanner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_copies', to='inventory.shelf'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['assigned_shelf'], name='inventory_b_assigne_842037_idx'),
        ),
    ]
