# Generated by Django 5.0.4 on 2026-04-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_shelfslot_unique_together_and_more'),
        ('scanner', '0003_remove_missingreport_expected_slot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShelfSlot',
        ),
    ]
